<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <Configurations>Debug;Release;Debug 1.12+;Release 1.12+;Debug 1.20.2+;Release 1.20.2+</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug 1.12+|AnyCPU'">
    <DefineConstants>$(DefineConstants);VERSION_1_12_ABOVE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release 1.12+|AnyCPU'">
    <DefineConstants>$(DefineConstants);VERSION_1_12_ABOVE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug 1.20.2+|AnyCPU'">
    <DefineConstants>$(DefineConstants);VERSION_1_20_2_ABOVE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release 1.20.2+|AnyCPU'">
    <DefineConstants>$(DefineConstants);VERSION_1_20_2_ABOVE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Utils\VectorTest.cs~RF8786957.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnderOverhaul.EnderDynamics\EnderOverhaul.EnderDynamics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>